---

- name: Create required directories for alfresco
  file:
    state: directory
    path: "{{ item }}"
    owner: alfresco
    group: alfresco
  with_items:
    - /alfresco/tomcat/shared/classes/alfresco/extension/subsystems/Authentication/ldap/ldap1/
    - /alfresco/tomcat/shared/classes/alfresco/extension/subsystems/Authentication/ldap-ad/ldap1/
    - /alfresco/tomcat/webapps/ROOT
    - /srv/content
    - /srv/cache
    - /alfresco/tomcat/shared/classes/alfresco/extension/license

- name: Get our alfresco installation binary and license
  s3:
    bucket: "{{ artifact_bucket }}"
    object: "/alfresco/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: get
  with_items:
    - alfresco-installer-{{ alfresco_version|default('5.2') }}-linux-x64.bin
    - alfresco-ent-{{ alfresco_version|default('5.2') }}-NOMS.lic

- name: Install our alfresco binary
  command: "JAVA_HOME=/usr/java/latest \
            ./tmp/alfresco-installer-{{ alfresco_version|default('5.2') }}-linux-x64.bin \
            --prefix /alfresco \
            --alfresco_admin_password {{ alfreso_admin_password|default('admin') }} \
             --disable-components postgres"

- name: Move our license to the correct directory
  command: "mv alfresco-ent-{{ alfresco_version|default('5.2') }}-NOMS.lic \
            /alfresco/tomcat/shared/classes/alfresco/extension/license/."

- name: Ensure our path has correct attributes
  file:
    path: /alfresco
    recurse: true
    owner: alfresco
    mode: 0775

