---

- name: Create required directories for alfresco
  file:
    state: directory
    path: "{{ item }}"
    owner: alfresco
    group: alfresco
  with_items:
    - /alfresco/tomcat/shared/classes/alfresco/extension/subsystems/Authentication/ldap/ldap1/
    - /alfresco/tomcat/shared/classes/alfresco/extension/subsystems/Authentication/ldap-ad/ldap1/
    - /alfresco/tomcat/webapps/ROOT
    - /srv/content
    - /srv/cache
    - /alfresco/tomcat/shared/classes/alfresco/extension/license

- name: Ensure our path has correct attributes
  file:
    path: "{{ item }}"
    recurse: true
    owner: alfresco
    mode: 0775
  with_items:
    - /alfresco
    - /srv/content
    - /srv/cache

- name: Get our alfresco installation binary and license
  aws_s3:
    bucket: "{{ artifact_bucket }}"
    object: "/alfresco/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: get
  with_items:
    - alfresco-installer-{{ alfresco_version|default('5.2') }}-linux-x64.bin
    - alfresco-ent-{{ alfresco_version|default('5.2') }}-NOMS.lic
    - alfresco-global.properties

- name: Make our alfresco binary executable
  command: "chmod +x /tmp/alfresco-installer-{{ alfresco_version|default('5.2') }}-linux-x64.bin"
  warn: false

- name: Copy our installer template to the server
  copy:
    src: "{{ role_path }}/files/alfresco.properties"
    dest: /tmp/alfresco.properties
    remote_src: true

- name: Set our admin password
  lineinfile:
    path: /tmp/alfresco.properties
    regexp: "^ALF_PASSWORD"
    line: "alfresco_admin_password={{ alfresco_admin_password|default('admin') }}"

- name: Install our alfresco binary
  raw: "JAVA_HOME=/usr/bin/java \
             /tmp/alfresco-installer-{{ alfresco_version|default('5.2') }}-linux-x64.bin \
            --optionfile /tmp/alfresco.properties \
            --installer-language en"

- name: Move our license to the correct directory
  copy:
    src: "/tmp/alfresco-ent-{{ alfresco_version|default('5.2') }}-NOMS.lic"
    dest: /alfresco/tomcat/shared/classes/alfresco/extension/license/
    remote_src: true

- name: Move our configfile to the correct directory
  copy:
    src: "/tmp/alfresco-global.properties"
    dest: /alfresco/tomcat/shared/classes/alfresco-global.properties
    remote_src: true

- name: Ensure that alfresco has stopped
  service:
    name: alfresco
    state: stopped

- name: Clean up
  file:
    state: absent
    path: "/tmp/{{ item }}"
  with_items:
    - "alfresco-ent-{{ alfresco_version|default('5.2') }}-NOMS.lic"
    - "alfresco-installer-{{ alfresco_version|default('5.2') }}-linux-x64.bin"
    - "alfresco.properties"
    - "alfresco-global.properties"

- name: Modify the startupscript so we can run as a non priveleged user
  lineinfile:
    path: /etc/rc.d/init.d/alfresco
    regexp: "/alfresco/alfresco.sh start \"$2\""
    line: "su - alfresco -c \"/opt/Alfresco/alfresco.sh start $2\""

- name: Modify the startupscript so we can stop as a non priveleged user
  lineinfile:
    path: /etc/rc.d/init.d/alfresco
    regexp: "/alfresco/alfresco.sh stop \"$2\""
    line: "su - alfresco -c \"/opt/Alfresco/alfresco.sh stop $2\""
