---

- name: Set directory locations
  set_fact:
    alfresco_libs: /usr/share/tomcat/shared/lib
    alfresco_licence: /usr/share/tomcat/shared/classes/alfresco/extension/license
    alfresco_content: /srv/content
    alfresco_cache: /srv/cache
    alfresco_data: /srv/alf_data
    tomcat_shared: /usr/share/tomcat/shared/

- name: Create required directories for alfresco
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ alfresco_libs }}"
    - "{{ alfresco_license }}"
    - "{{ alfresco_content }}"
    - "{{ alfresco_cache }}"
    - "{{ alfresco_data }}"

- name: Set permissions on cache and content and data dirs
  file:
    dest: "{{ item }}"
    owner: tomcat
    group: tomcat
    recurse: true
  with_items:
    - "{{ alfresco_content }}"
    - "{{ alfresco_cache }}"
    - "{{ alfresco_data }}"

- name: Get our alfresco zips, amps and license
  aws_s3:
    bucket: "{{ artifact_bucket }}"
    object: "/alfresco/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: get
  with_items:
    - alfresco-content-services-platform-distributionzip-5.2.3.zip
    - alfresco-content-services-share-distribution-5.2.3.zip
    - alfresco-ent-5.2-NOMS.lic
    - alfresco-s3-connector-2.1.0.amp

- name: Uncompress our installers
  unarchive:
    src: "/tmp/{{ item }}"
    dest: "/tmp"
    remote_src: true
  with_items:
    - alfresco-content-services-platform-distributionzip-5.2.3.zip
    - alfresco-content-services-share-distribution-5.2.3.zip

- name: Copy folders to the correct location
  copy:
    src: "/tmp/{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
  with_items:
    - { src: "alfresco-content-services-platform-distributionzip-5.2.3/alf_data", dest: "/srv" }
    - { src: "alfresco-content-services-share-distributionzip-5.2.3/alf_data", dest: "/srv" }
    - { src: "alfresco-content-services-share-distributionzip-5.2.3/bin", dest: "/srv" }
    - { src: "alfresco-content-services-share-distributionzip-5.2.3/bin", dest: "/srv" }

- name: Copy our files to the correct locations
  copy:
    src: "/tmp/{{ item.src }}/{{ item.file }}"
    dest: "{{ item.dest }}/{{ item.file }}"
    remote_src: true
  with_items:
   - {
        file: "postgresql-9.4.1212.jar",
        src: "alfresco-content-services-platform-distributionzip-5.2.3/web-server/lib",
        dest: "{{ alfresco_libs }}"
    }
- name: Install our alfresco binary
  raw: "JAVA_HOME=/usr/bin/java \
             /tmp/alfresco-installer-{{ alfresco_version|default('5.2') }}-linux-x64.bin \
            --optionfile /tmp/alfresco.properties \
            --installer-language en"

- name: Move our license to the correct directory
  copy:
    src: "/tmp/alfresco-ent-{{ alfresco_version|default('5.2') }}-NOMS.lic"
    dest: /alfresco/tomcat/shared/classes/alfresco/extension/license/
    remote_src: true

- name: Move our configfile to the correct directory
  copy:
    src: "/tmp/alfresco-global.properties"
    dest: /alfresco/tomcat/shared/classes/alfresco-global.properties
    remote_src: true

- name: Ensure that alfresco has stopped
  service:
    name: alfresco
    state: stopped

- name: Clean up
  file:
    state: absent
    path: "/tmp/{{ item }}"
  with_items:
    - "alfresco-ent-{{ alfresco_version|default('5.2') }}-NOMS.lic"
    - "alfresco-installer-{{ alfresco_version|default('5.2') }}-linux-x64.bin"
    - "alfresco.properties"
    - "alfresco-global.properties"

- name: Modify the startupscript so we can run as a non priveleged user
  lineinfile:
    path: /etc/rc.d/init.d/alfresco
    regexp: "/alfresco/alfresco.sh start \"$2\""
    line: "su - alfresco -c \"/opt/Alfresco/alfresco.sh start $2\""

- name: Modify the startupscript so we can stop as a non priveleged user
  lineinfile:
    path: /etc/rc.d/init.d/alfresco
    regexp: "/alfresco/alfresco.sh stop \"$2\""
    line: "su - alfresco -c \"/opt/Alfresco/alfresco.sh stop $2\""
