---

- name: Set open office facts
  set_fact:
    libre_office_version: "{{ libre_office_version|default('6.0.5') }}"
    libre_office_url:  "http://download.documentfoundation.org/libreoffice/stable/{{ libre_office_version|default('6.0.5') }}/rpm/x86_64/LibreOffice_{{ libre_office_version|default('6.0.5') }}_Linux_x86-64_rpm.tar.gz"

- name: Download libre-office
  get_url:
    url: "{{ libre_office_url }}"
    dest: "/tmp/lo_{{ libre_office_version }}.tar.gz"

- name: Uncompress our installer
  command: "tar -xf /tmp/lo_{{ libre_office_version }}.tar.gz -C /tmp"

- name: Run our installer
  command: "bash /tmp/LibreOffice_6.0.5.2_Linux_x86-64_rpm/install /tmp/LibreOffice_{{ libre_office_version }}.2_Linux_x86-64_rpm /alfresco/libreoffice"
  become: true
  become_user: alfresco

- name: Move our binary as lo munges paths a bit
  shell: mv /alfresco/libreoffice/opt/libreoffice6.0/* /alfresco/libreoffice/

- name: Cleanup
  file:
    state: absent
    path: "/tmp/{{ item }}"
  with_items:
    - "lo_{{ libre_office_version }}.tar.gz"
    - "/tmp/LibreOffice_{{ libre_office_version }}.2_Linux_x86-64_rpm/"