---

- name: Get oracle java jdk
  shell: "wget --no-cookies --no-check-certificate --header \"Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie\" \"http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.rpm\" \
          -o /tmp/jdk.rpm"

- name: Install oracle java
  shell: "yum localinstall -y /tmp/jdk.rpm"

- name: Install/upgrade the epel repo from remote
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: latest

- name: Update our system
  yum:
    name: '*'
    state: latest

- name: Install required packages
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ alfresco_vars.packages }}"
