---
common_name: test-ansible-role-solr
system:
  packages:
    - deltarpm
    - dpkg
    - cairo
    - cairo-devel
    - cups
    - cups-devel
    - cups-libs
    - fontconfig
    - tomcat
    - libICE
    - libSM
    - libXext
    - libXinerama
    - libXrender
    - libGLU
    - mesa-libGLU
    - patch
    - rsync
    - rsyslog
    - wget
    - ImageMagick
    - vim
    - curl
    - ghostscript
    - unzip
install_jdk: true
artifact_bucket: tf-eu-west-2-hmpps-eng-dev-config-s3bucket
alfresco_artifact_bucket: hmpps-eng-dev-alfresco-rpms
alfresco_build_path: releases/release/R3.6.4/3
alfresco_version_number: release/R3.6.4
